### ISSUE TITLE
Check the background composition from MC

### ISSUE THREAD

**Issue by thongonary** [cms-lpc-llp/DelayedPhotonID#1]
Use 2016 MC from Zhicai to reproduce Gillian's BDT.

**Comment by thongonary** [comment]
Selections: 
```
event_cut = 'n_Jets > 2 && (HLTDecision[81] == 1) && n_Photons == 2 '
pho_cut = ' && pho1Pt > 70 && abs(pho1Eta)<1.4442 && pho1HoverE < 0.04596 && 
                   pho1R9 > 0.9 && pho1SigmaIetaIeta < 0.014 && pho1passIsoLoose_comboIso && 
                   pho1Sminor < 0.4 '
met_cut = " && Flag_HBHENoiseFilter == 1 && Flag_HBHEIsoNoiseFilter ==1 && 
                   Flag_goodVertices == 1 && Flag_eeBadScFilter == 1 && 
                   Flag_EcalDeadCellTriggerPrimitiveFilter == 1 && 
                   Flag_CSCTightHaloFilter == 1  && 
                   Flag_badMuonFilter == 1 && Flag_badGlobalMuonFilter == 0 && 
                   Flag_duplicateMuonFilter == 0 "
```
Lumi: 3592 pb^-1
Cross section taken from https://github.com/cms-lpc-llp/DelayedPhotonID/blob/master/data/all_bkg_back.list
Reproducible code: https://github.com/cms-lpc-llp/DelayedPhotonID/blob/master/visualization/BackgroundComposition.ipynb

![MET](https://user-images.githubusercontent.com/10479549/75655637-22702700-5c17-11ea-9947-d43e768336f3.png)

Takeaway: The dominating background is GJets. QCD and diphoton are negligible.

**Comment by thongonary** [comment]
If I remove all the cuts and only keep the trigger requirement (`HLTDecision[81] == 1`), the composition becomes like this:

![bkg_hltcutonly](https://user-images.githubusercontent.com/10479549/75658030-58fc7080-5c1c-11ea-9555-eff5c892c97d.png)

**Comment by sixie** [comment]
How's it possible that when you require additional Photon ID cuts and isolation, and you actually kill the prompt photons and enhance the fake photons? seems to be the opposite as expected...

**Comment by zhangzc11** [comment]
> Selections:
> 
> ```
> event_cut = 'n_Jets > 2 && (HLTDecision[81] == 1) && n_Photons == 2 '
> pho_cut = ' && pho1Pt > 70 && abs(pho1Eta)<1.4442 && pho1HoverE < 0.04596 && 
>                    pho1R9 > 0.9 && pho1SigmaIetaIeta < 0.014 && pho1passIsoLoose_comboIso && 
>                    pho1Sminor < 0.4 '
> met_cut = " && Flag_HBHENoiseFilter == 1 && Flag_HBHEIsoNoiseFilter ==1 && 
>                    Flag_goodVertices == 1 && Flag_eeBadScFilter == 1 && 
>                    Flag_EcalDeadCellTriggerPrimitiveFilter == 1 && 
>                    Flag_CSCTightHaloFilter == 1  && 
>                    Flag_badMuonFilter == 1 && Flag_badGlobalMuonFilter == 0 && 
>                    Flag_duplicateMuonFilter == 0 "
> ```
> 
> Lumi: 3592 pb^-1
> Cross section taken from https://github.com/cms-lpc-llp/DelayedPhotonID/blob/master/data/all_bkg_back.list
> Reproducible code: https://github.com/cms-lpc-llp/DelayedPhotonID/blob/master/visualization/BackgroundComposition.ipynb
> 
> ![MET](https://user-images.githubusercontent.com/10479549/75655637-22702700-5c17-11ea-9947-d43e768336f3.png)
> 
> Takeaway: The dominating background is GJets. QCD and diphoton are negligible.

Aren't the QCD and GJets similar in size based on the plot? the y-axis is in log-scale.

**Comment by thongonary** [comment]
OK, scrap the former plots. I think there were several bugs. Here is what the correct ones should look like: 
Selections:
```
event_cut = 'n_Jets > 2 && (HLTDecision[81] == 1) && n_Photons == 2 '
pho_cut = ' && pho1Pt > 70 && abs(pho1Eta)<1.4442 && \
                        pho1HoverE < 0.04596 && pho1R9 > 0.9 && \
                        pho1SigmaIetaIeta < 0.014 && pho1passIsoLoose_comboIso && \
                        pho1Sminor < 0.4 '
met_cut = " && Flag_HBHENoiseFilter == 1 && Flag_HBHEIsoNoiseFilter ==1 && \
                   Flag_goodVertices == 1 && Flag_eeBadScFilter == 1 && \
                   Flag_EcalDeadCellTriggerPrimitiveFilter == 1 && \
                   Flag_CSCTightHaloFilter == 1  && \
                   Flag_badMuonFilter == 1 && Flag_badGlobalMuonFilter == 0 && \
                   Flag_duplicateMuonFilter == 0 "
```
On log scale:
![download](https://user-images.githubusercontent.com/10479549/75733111-3ebca400-5ca9-11ea-9a6a-c519bce414d6.png)

On linear scale: 
![download](https://user-images.githubusercontent.com/10479549/75733161-614ebd00-5ca9-11ea-8899-0fd91a39fb4b.png)

---
Now if I only keeps the trigger cut:
```
HLTDecision[81] == 1
```
On log scale:
![download](https://user-images.githubusercontent.com/10479549/75735043-69f5c200-5cae-11ea-930f-3c75f5fae81b.png)

On linear scale:
![download](https://user-images.githubusercontent.com/10479549/75735074-80038280-5cae-11ea-910e-1d5f2e4b5eb8.png)


Takeaway: The only major background being reduced after the isolation etc cuts is QCD, which is reasonable.

**Comment by thongonary** [comment]
FYI @cms-lpc-llp/delayedphoton

**Comment by thongonary** [comment]
So I guess the trigger-cut-only plot is similar to what @zhangzc11 observed (50/50 between photon+jets and QCD, with small diphoton contribution). 

Which I guess contradicts to what @sixie believes in the usual diphoton analysis...

**Comment by thongonary** [comment]
```
Using cross section of 308.3 for /mnt/hadoop/store/group/phys_susy/razor/Run2Analysis/DelayedPhotonAnalysis/2016/orderByPt/withcut/DelayedPhoton_DiPhotonJetsBox_M40_80-Sherpa.root with luminosity of 35922.0 pb-1
+ nPhoton>1: 31500.94 (100.00%)
+ photonIsEB: 21948.56 (69.68%)
+ photonPT: 8963.70 (28.46%)
+ METFilters: 8942.58 (28.39%)
+ photonR9: 4560.75 (14.48%)
+ photonHoverE: 4458.18 (14.15%)
+ photonIetaeta: 4420.92 (14.03%)
+ photonSminor: 4411.98 (14.01%)
+ photonIsolation: 3773.02 (11.98%)
+ nJets: 668.42 (2.12%)
+ Trigger: 505.99 (1.61%)
```

**Comment by thongonary** [comment]
So it turns out there was something wrong with the MET filter that killed the entire DiPhoton MGG > 80 GeV bin:
```
Using cross section of 87.54 for /mnt/hadoop/store/group/phys_susy/razor/Run2Analysis/DelayedPhotonAnalysis/2016/orderByPt/withcut/DelayedPhoton_DiPhotonJetsBox_MGG-80toInf_13TeV-Sherpa.root with luminosity of 35922.0 pb-1
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
+ None: 1144685.92 (100.00%)
+ nPhoton>1: 401222.29 (35.05%)
+ photonIsEB: 288719.40 (25.22%)
+ photonPT>70: 149887.92 (13.09%)
+ METFilters: 0.00 (0.00%)
+ photonR9>0.9: 0.00 (0.00%)
+ photonHoverE<0.046: 0.00 (0.00%)
+ photonIetaeta<0.014: 0.00 (0.00%)
+ photonSminor<0.4: 0.00 (0.00%)
+ photonIsolationLoose: 0.00 (0.00%)
+ nJets>2: 0.00 (0.00%)
+ Trigger: 0.00 (0.00%)
```

Removing the MET filter requirements, the composition became:
```
            event_cut = 'n_Jets > 2 && (HLTDecision[81] == 1) && n_Photons == 2 '
            pho_cut = ' && pho1Pt > 70 && abs(pho1Eta)<1.4442 && \
                        pho1HoverE < 0.04596 && pho1R9 > 0.9 && \
                        pho1SigmaIetaIeta < 0.014 && pho1passIsoLoose_comboIso && \
                        pho1Sminor < 0.4 '
```
Log scale:
![download](https://user-images.githubusercontent.com/10479549/75743041-7be25f80-5cc4-11ea-82ff-13762e67cff3.png)

Linear scale:
![download](https://user-images.githubusercontent.com/10479549/75743059-8a307b80-5cc4-11ea-897c-709c3631cc95.png)

**Comment by thongonary** [comment]
Running the sequence again without the MET filter, we suspected nJets cut is the one reducing DiPhoton the most. But that cut actually reduces other backgrounds (QCD, GJets) just as strong.

DiJet MGG 80ToInf:
```
Using cross section of 87.54 for /mnt/hadoop/store/group/phys_susy/razor/Run2Analysis/DelayedPhotonAnalysis/2016/orderByPt/withcut/DelayedPhoton_DiPhotonJetsBox_MGG-80toInf_13TeV-Sherpa.root with luminosity of 35922.0 pb-1
+ None: 1144685.92 (100.00%)
+ Trigger: 440425.71 (38.48%)
+ nPhoton>1: 260738.46 (22.78%)
+ photonIsEB: 210787.96 (18.41%)
+ photonPT>70: 112693.44 (9.84%)
+ photonR9>0.9: 91401.22 (7.98%)
+ photonHoverE<0.046: 91267.71 (7.97%)
+ photonIetaeta<0.014: 91198.32 (7.97%)
+ photonIsolationLoose: 81920.91 (7.16%)
+ photonSminor<0.4: 81915.33 (7.16%)
+ nJets>2: 7248.13 (0.63%)
```
DiJet M 40To80:
```
Using cross section of 308.3 for /mnt/hadoop/store/group/phys_susy/razor/Run2Analysis/DelayedPhotonAnalysis/2016/orderByPt/withcut/DelayedPhoton_DiPhotonJetsBox_M40_80-Sherpa.root with luminosity of 35922.0 pb-1
+ None: 843586.82 (100.00%)
+ Trigger: 104959.18 (12.44%)
+ nPhoton>1: 14966.17 (1.77%)
+ photonIsEB: 11995.61 (1.42%)
+ photonPT>70: 4319.25 (0.51%)
+ photonR9>0.9: 2739.50 (0.32%)
+ photonHoverE<0.046: 2712.60 (0.32%)
+ photonIetaeta<0.014: 2695.09 (0.32%)
+ photonIsolationLoose: 2296.66 (0.27%)
+ photonSminor<0.4: 2295.11 (0.27%)
+ nJets>2: 508.32 (0.06%)
```
GJets 200To400:
```
Using cross section of 2305.0 for /mnt/hadoop/store/group/phys_susy/razor/Run2Analysis/DelayedPhotonAnalysis/2016/orderByPt/withcut/DelayedPhoton_GJets_HT-200To400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root with luminosity of 35922.0 pb-1
+ None: 46957022.88 (100.00%)
+ Trigger: 1050272.83 (2.24%)
+ nPhoton>1: 555974.09 (1.18%)
+ photonIsEB: 390363.49 (0.83%)
+ photonPT>70: 270304.92 (0.58%)
+ photonR9>0.9: 157059.05 (0.33%)
+ photonHoverE<0.046: 156227.17 (0.33%)
+ photonIetaeta<0.014: 150511.25 (0.32%)
+ photonIsolationLoose: 80693.07 (0.17%)
+ photonSminor<0.4: 80631.66 (0.17%)
+ nJets>2: 16667.36 (0.04%)
```
QCD HT 200To300:
```
Using cross section of 1712000.0 for /mnt/hadoop/store/group/phys_susy/razor/Run2Analysis/DelayedPhotonAnalysis/2016/orderByPt/withcut/DelayedPhoton_QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root with luminosity of 35922.0 pb-1
+ None: 4999038947.90 (100.00%)
+ Trigger: 5183638.47 (0.10%)
+ nPhoton>1: 1831434.25 (0.04%)
+ photonIsEB: 1200229.37 (0.02%)
+ photonPT>70: 589193.25 (0.01%)
+ photonR9>0.9: 191946.39 (0.00%)
+ photonHoverE<0.046: 191946.39 (0.00%)
+ photonIetaeta<0.014: 168226.98 (0.00%)
+ photonIsolationLoose: 20135.33 (0.00%)
+ photonSminor<0.4: 20135.33 (0.00%)
+ nJets>2: 3069.97 (0.00%)
```

Here is the plot without the nJets cut:
On log scale:
![download](https://user-images.githubusercontent.com/10479549/75824723-e0e79500-5d58-11ea-9085-575e269fbcff.png)

On linear scale:
![download](https://user-images.githubusercontent.com/10479549/75824762-f1980b00-5d58-11ea-9a45-a2c39e84f689.png)

**Comment by thongonary** [comment]
@sixie any comment?

**Comment by sixie** [comment]
diphoton is still not dominant. It looks similar to the previous plot, including the jet cut.
What do you get if you also remove this cut: pho1Sminor < 0.4

**Comment by thongonary** [comment]
Essentially doesn't change anything (as expected from the printout in my previous comment).
```
            event_cut = '(HLTDecision[81] == 1) && n_Photons == 2 '
            pho_cut = ' && pho1Pt > 70 && abs(pho1Eta)<1.4442 && \
                        pho1HoverE < 0.04596 && pho1R9 > 0.9 && \
                        pho1SigmaIetaIeta < 0.014 && pho1passIsoLoose_comboIso '
```
Log scale: 
![download](https://user-images.githubusercontent.com/10479549/75899354-45096800-5df0-11ea-8eb1-4bc1dd54f09b.png)

Lienar scale:
![download](https://user-images.githubusercontent.com/10479549/75899406-56527480-5df0-11ea-9dcf-ff1b87707d6e.png)

@sixie What was the trigger you use in other diphoton analysis?

**Comment by sixie** [comment]
the Higgs diphoton trigger. So maybe it’s actually just because your photon id is super loose. Maybe it’s ok...

**Comment by thongonary** [comment]
Just want to add the fact that if I remove the photon requirement (which is a reasonable thing to do if I want to train on both pho1 and pho2), I get the following:
```
n_Jets > 2 && (HLTDecision[81] == 1) && n_Photons == 2 
```
![download](https://user-images.githubusercontent.com/10479549/75942225-b116bb00-5e46-11ea-8548-27ab0fce2aed.png)
ie, 50/50 between gamma jets and QCD. I think this should be the same thing that Zhicai remembers.

**Comment by sixie** [comment]
Ok, so we should train in this proportion of fakes vs prompt. If you count all objects it will be 3:1 fake to prompt

**Comment by cmorgoth** [comment]
can we check if we apply the standard photon ID +ISO we enhance diphoton contribution as expected? At the moment we are only guessing that will be the case.

**Comment by thongonary** [comment]
> can we check if we apply the standard photon ID +ISO we enhance diphoton contribution as expected? At the moment we are only guessing that will be the case. I am afraid that the inputs could just be wrong if we don't check that we can reproduce the expected behavior.

Here is the composition with standard photon ID on both leading and subleading photon:
```
  event_cut = 'n_Jets > 2 && (HLTDecision[81] == 1) && n_Photons == 2 '
  pho_cut = ' && pho1passIsoLoose && pho1SigmaIetaIeta < 0.0106 && \
                      pho2passIsoLoose && pho2SigmaIetaIeta < 0.0106'
```
![download](https://user-images.githubusercontent.com/10479549/76025694-5632a180-5ee2-11ea-8812-25646e376d00.png)

Very close to 50% diphoton and @sixie's happiness.

**Comment by thongonary** [comment]
@cms-lpc-llp/delayedphoton So based on the trigger cuts
```
cuts in the Pho42_25 trigger for leading (sub-leading) photon:
pt > 42 (25) GeV
R9 > 0.85 (0.85)
H/E < 0.1 (0.1)
SigmaIetaIeta < 0.024, 0.04 (0.024, 0.04) for EB, EE photons
EcalPFClusterIso < 8.0 (8.0) GeV
HcalPFClusterIso < 5.0 (5.0) GeV
HollowTrackIso < 8.0 (8.0) GeV
```
I remade the background component plot with a bit tighter requirements and also requiring the leading photon in the barrel:
```
event_cut = '(HLTDecision[81] == 1) && n_Photons == 2 '
pho_cut = ' && pho1Pt > 50 && abs(pho1Eta)<1.4442 && \
                   abs(pho1HoverE) < 0.08 && pho1R9 > 0.9 && \
                  abs(pho1SigmaIetaIeta) < 0.020 && abs(pho1ecalPFClusterIso) < 7.0 && 
                  abs(pho1hcalPFClusterIso) < 5.0 && abs(pho1trkSumPtHollowConeDR03) < 7.0'
```

It seems we have a sizeable fraction of diphoton and very few QCD:
![download](https://user-images.githubusercontent.com/10479549/76262539-d70ed780-6219-11ea-81bf-c657cbf876b5.png)

**Comment by thongonary** [comment]
Adding number of jets > 2 and only diphoton stays...
```
event_cut = '(HLTDecision[81] == 1) && n_Photons == 2  && nJets > 2'
pho_cut = ' && pho1Pt > 50 && abs(pho1Eta)<1.4442 && \
                   abs(pho1HoverE) < 0.08 && pho1R9 > 0.9 && \
                   abs(pho1SigmaIetaIeta) < 0.020 && \
                   abs(pho1ecalPFClusterIso) < 7.0 && \
                   abs(pho1hcalPFClusterIso) < 5.0 && \
                   abs(pho1trkSumPtHollowConeDR03) < 7.0'
```
![download](https://user-images.githubusercontent.com/10479549/76262811-995e7e80-621a-11ea-8c20-2a2603974daa.png)

**Comment by thongonary** [comment]
Adding number of jets > 2 requirement and QCD rate seems to be similar to diphoton's:

```
event_cut = '(HLTDecision[81] == 1) && n_Photons == 2  && n_Jets > 2'
pho_cut = ' && pho1Pt > 50 && abs(pho1Eta)<1.4442 && \
                   abs(pho1HoverE) < 0.08 && pho1R9 > 0.9 && \
                   abs(pho1SigmaIetaIeta) < 0.020 && \
                   abs(pho1ecalPFClusterIso) < 7.0 && \
```
![download](https://user-images.githubusercontent.com/10479549/76263059-2b668700-621b-11ea-919f-0c2505a8fbaa.png)
